import { GameTag } from './game-categories';

export const GAME_MECHANICS: GameTag[] = [
  { name: 'Dice Rolling', description: 'Outcomes are determined by rolling dice' },
  { name: 'Hand Management', description: 'Players decide which cards to play, hold, or discard each turn' },
  { name: 'Set Collection', description: 'Players score by gathering matching or complementary groups of items' },
  { name: 'Tile Placement', description: 'Players place tiles to build a shared or personal board' },
  { name: 'Worker Placement', description: 'Players place worker tokens on action spaces to claim them before others' },
  { name: 'Deck Building', description: 'Players acquire cards to improve their personal deck during the game' },
  { name: 'Area Control', description: 'Players compete to dominate regions of the board with the most pieces' },
  { name: 'Cooperative Play', description: 'All players win or lose together as a team against the game' },
  { name: 'Trading', description: 'Players exchange resources or cards with each other' },
  { name: 'Auction / Bidding', description: 'Players compete for items by bidding their resources or money' },
  { name: 'Card Drafting', description: 'Players pick cards from a shared pool and pass the rest to the next player' },
  { name: 'Trick Taking', description: 'Players play cards in rounds; the highest or lowest card wins the trick' },
  { name: 'Push Your Luck', description: 'Players choose whether to risk a good result for a potentially better one' },
  { name: 'Press Your Luck', description: 'Players keep pressing for more until they choose to stop or go bust' },
  { name: 'Tableau Building', description: 'Players build a personal play area of cards that interact and score together' },
  { name: 'Hand Building', description: 'Players construct a hand of cards over the course of the game' },
  { name: 'Grid Movement', description: 'Pieces move across a grid of squares or hexes' },
  { name: 'Point-to-Point Movement', description: 'Pieces move between fixed nodes connected by paths on the board' },
  { name: 'Modular Board', description: 'The board is assembled from tiles each game, creating a different layout' },
  { name: 'Route Building', description: 'Players build connected paths or roads across the board' },
  { name: 'Network Building', description: 'Players connect nodes to form the most efficient or extensive network' },
  { name: 'Pattern Building', description: 'Players arrange pieces to match or create scoring patterns' },
  { name: 'Hex-and-Counter', description: 'Uses hexagonal spaces and cardboard counters, common in wargames' },
  { name: 'Enclosure', description: 'Players surround and claim areas of the board' },
  { name: 'Engine Building', description: 'Players build an interconnected system that generates increasing output over time' },
  { name: 'Resource Management', description: 'Players collect and spend resources like wood, stone, or gold' },
  { name: 'Market', description: 'Players buy and sell goods at prices that shift based on supply and demand' },
  { name: 'Income', description: 'Players receive a regular supply of resources each round' },
  { name: 'Tech Trees / Upgrades', description: 'Players unlock improvements that enhance their abilities over time' },
  { name: 'Commodity Speculation', description: 'Players invest in goods hoping their value will rise' },
  { name: 'Bluffing', description: 'Players mislead others about their cards, role, or intentions' },
  { name: 'Deduction', description: 'Players use clues to logically determine hidden information' },
  { name: 'Hidden Roles', description: 'Players have secret roles that change their win condition' },
  { name: 'Hidden Movement', description: 'One player moves secretly while others try to track them down' },
  { name: 'Negotiation', description: 'Players make verbal agreements and deals with each other' },
  { name: 'Secret Unit Deployment', description: 'Players secretly place units before simultaneously revealing them' },
  { name: 'Memory', description: 'Players must remember the location or content of hidden items' },
  { name: 'Voting', description: 'Players collectively decide outcomes by casting votes' },
  { name: 'Action Points', description: 'Players have a budget of points to spend on different actions each turn' },
  { name: 'Variable Player Powers', description: 'Each player has unique abilities that change how they play' },
  { name: 'Simultaneous Action Selection', description: 'All players secretly choose their actions at the same time then reveal' },
  { name: 'Role Selection', description: 'Players choose from a set of roles that grant different abilities each round' },
  { name: 'Action Queue', description: 'Players plan and commit to a sequence of future actions in advance' },
  { name: 'Rondel', description: 'Players move a token around a wheel to select which actions are available' },
  { name: 'Time Track', description: 'Players advance on a time track; the player furthest behind always goes next' },
  { name: 'Legacy / Campaign', description: 'The game permanently changes between sessions based on what happened' },
  { name: 'Storytelling', description: 'Players narrate a story, making choices that affect the outcome' },
  { name: 'Choose Your Own Adventure', description: 'Players make decisions at branching points in a narrative' },
  { name: 'Scenario / Mission', description: 'Games are structured around discrete scenarios with specific goals' },
  { name: 'Bag Building', description: 'Players add and remove tokens from a bag, drawing randomly each turn' },
  { name: 'Roll & Write', description: 'Players roll dice and fill in a personal scoresheet with results' },
  { name: 'Flip & Write', description: 'Players flip cards instead of rolling dice, then record results' },
  { name: 'Polyomino', description: 'Players place Tetris-like shaped pieces to fill a grid efficiently' },
  { name: 'Drafting', description: 'Players take turns selecting items one at a time from a shared pool' },
  { name: 'Real-Time', description: 'All players act simultaneously under time pressure with no turns' },
  { name: 'Solo / Solitaire', description: 'Designed to be played alone against the game itself' },
  { name: 'Semi-Cooperative', description: 'Players cooperate against the game but there is still an individual winner' },
  { name: 'Dungeon Crawl', description: 'Players explore rooms, fight enemies, and collect rewards' },
  { name: 'Tower Defense', description: 'Players build defenses to repel waves of incoming enemies' },
];
